### ISSUE TITLE
CentOS 7.0 support

### ISSUE THREAD

**Issue by gdhbashton** [seporaitis/yum-s3-iam#29] opened 2014-11-14 11:53 UTC
Hullo,

We've been using this plugin for months on CentOS 6.5 AMI's without any problem (thank you!) - the IAM EC2 role is always reliably picked up.  Today I'm starting to use a CentOS 7.0 AMI and the plugin is failing.  When I `yum makecache` I can see `Loaded plugins: fastestmirror, s3iam` however the yum run fails:

```
https://sit-yumbucket-rbix7r3dlq8j-s3bucket-8trs8qdn31lj.s3.amazonaws.com/repos/puppet/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
```

The EC2 instance definitely does have a role defined, since if I use the native awscli (and hence the IAM EC2 roles) I can read the repomd.xml just fine...

```
[root@bastion-iea61640f ~]# aws s3 cp s3://sit-yumbucket-rbix7r3dlq8j-s3bucket-8trs8qdn31lj/repos/puppet/repodata/repomd.xml /tmp
download: s3://sit-yumbucket-rbix7r3dlq8j-s3bucket-8trs8qdn31lj/repos/puppet/repodata/repomd.xml to ../tmp/repomd.xml
```

```
curl http://169.254.169.254/latest/meta-data/iam/security-credentials/
sit-bastion1-SSUO17B1DRF-RootRole-T63LJKQOB5NB
```

When I `tcpdump -i eth0 -n host 169.254.169.254` whilst running `yum makecache` there is no network traffic - the credentials are not being looked up by the plugin. My repo definition is:

```[itvs3]
name=itv-s3
baseurl=https://sit-yumbucket-rbix7r3dlq8j-s3bucket-8trs8qdn31lj.s3.amazonaws.com/repos/puppet
metadata_expire=10s
enabled=1
s3_enabled=1
gpgcheck=0
```

How can I get more info / debug about what the plugin is doing 'behind the scenes'?

FWIW, I used the official CentOS 7 AMI on the Marketplace: https://aws.amazon.com/marketplace/pp/B00O7WM7QW

Cheers,
Gavin.

**Comment by jorhett** [comment] 2015-08-17 20:37
This is working for me since the merge. Can we get a bump on the rpm version created?

**Comment by mbrossard** [comment] 2015-11-04 02:26
We just bumped the version and the problem is fixed. Closing this issue.

**Closed by mbrossard** 2015-11-04 02:26 UTC
